[package]
name = "horsenuggets/chalk-luau"
description = "A terminal string styling library for Luau."
version = "0.0.0"
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/horsenuggets/chalk-luau"
include = [
    "default.project.json",
    "init.luau",
    "LICENSE",
    "README.md",
    "Source",
    "Source/**",
    "wally.toml",
]
exclude = ["**"]

[dependencies]

[dev-dependencies]
Testable = "horsenuggets/testable@0.1.0"
