[package]
name = "horsenuggets/chalk-luau"
description = "A template for creating Luau packages."
version = "0.0.0"
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/horsenuggets/chalk-luau"
